### ISSUE TITLE
Fix typo in README

### ISSUE THREAD

**Issue by abbycabs** [abbycabs/osd-openjs#1]
It should be Canada (not Cananda!) 🇨‍🇦

**Comment by acabunoc** [comment]
🍪 that's a funny typo

**Comment by acabunoc** [comment]
hey, I think I can fix this typo!

**Comment by mcninja117** [comment]
🐈‍⬛ My cat missed the typo too!

**Comment by PaulaPaul** [comment]
@abbycabs does GitHub have spellcheck? ;)
